INSERT INTO ESTADO (nome) VALUES('Acre'); 
INSERT INTO ESTADO (nome) VALUES('Alagoas'); 
INSERT INTO ESTADO (nome) VALUES('Amazonas');
INSERT INTO ESTADO (nome) VALUES('Amapá');
INSERT INTO ESTADO (nome) VALUES('Bahia');
INSERT INTO ESTADO (nome) VALUES('Ceará');
INSERT INTO ESTADO (nome) VALUES('Distrito Federal');
INSERT INTO ESTADO (nome) VALUES('Espírito Santo');
INSERT INTO ESTADO (nome) VALUES('Goiás');
INSERT INTO ESTADO (nome) VALUES('Maranhão');
INSERT INTO ESTADO (nome) VALUES('Minas Gerais');
INSERT INTO ESTADO (nome) VALUES('Mato Grosso do Sul');
INSERT INTO ESTADO (nome) VALUES('Mato Grosso');
INSERT INTO ESTADO (nome) VALUES('Pará');
INSERT INTO ESTADO (nome) VALUES('Paraíba');
INSERT INTO ESTADO (nome) VALUES('Pernambuco');
INSERT INTO ESTADO (nome) VALUES('Piauí');
INSERT INTO ESTADO (nome) VALUES('Paraná');
INSERT INTO ESTADO (nome) VALUES('Rio de Janeiro');
INSERT INTO ESTADO (nome) VALUES('Rio Grande do Norte');
INSERT INTO ESTADO (nome) VALUES('Rondônia');
INSERT INTO ESTADO (nome) VALUES('Roraima');
INSERT INTO ESTADO (nome) VALUES('Rio Grande do Sul');
INSERT INTO ESTADO (nome) VALUES('Santa Catarina');
INSERT INTO ESTADO (nome) VALUES('Sergipe');
INSERT INTO ESTADO (nome) VALUES('São Paulo');
INSERT INTO ESTADO (nome) VALUES('Tocantins');

INSERT INTO CIDADE (nome, estado_id) VALUES ('Afonso Cláudio', 8);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Água Doce do Norte', 8);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Tarauacá', 1);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Xapuri', 1);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Traipu', 2);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Viçosa', 2);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Amapá', 4);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Calçoene', 4);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Alvarães', 3);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Amaturá', 3);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Anamã', 3);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Abaíra', 5);
INSERT INTO CIDADE (nome, estado_id) VALUES ('Abaré', 5);

INSERT INTO CLIENTE (nome, sexo, data_nascimento, idade, cidade_id) VALUES ('Luiz Miranda Silva Filho', 'M', '1996-09-17', 25, 1); 
INSERT INTO CLIENTE (nome, sexo, data_nascimento, idade, cidade_id) VALUES ('Laura Maria Souza Pontes', 'F', '1985-01-01', 37, 3);
INSERT INTO CLIENTE (nome, sexo, data_nascimento, idade, cidade_id) VALUES ('Roberto Cavalcanti Neto', 'M', '1978-06-12', 43, 5);
INSERT INTO CLIENTE (nome, sexo, data_nascimento, idade, cidade_id) VALUES ('Maria Fernanda Torres', 'F', '2020-04-03', 2, 8);